source 'http://git.17gwx.com/iOS/SQSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
#use_modular_headers!

platform :ios, '10.0'

target 'SQHYBRID_Example' do
  pod 'SQHYBRID', :path => '../'
  
  target 'SQHYBRID_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
